spring:
  config:
    import:
      - classpath:app.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/limits_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog-master.yaml
    enabled: true
server:
  port: 8080